### ISSUE TITLE
Invalid usage of length in frontend_loader.js 

### ISSUE THREAD

**Issue by DigitalGoldfish** [EXADS/exads-adblock#1]
The following line is in frontend_loader.js in the serve function:

` if ((typeof exo99HL3903jjdxtrnLoad != "undefined" && exo99HL3903jjdxtrnLoad) || zone_params.length < 1) {`

zone_params is an object here, not an array. you probably mean to check if either banner or popup attribute is defined on the zone_params object. As it currently is the second part of the if condition will always return false.

**Comment by golikov** [comment]
Thanks. This was fixed.
