### ISSUE TITLE
Way around this easylist rule

### ISSUE THREAD

**Issue by slayerduck** [EXADS/exads-adblock#7]
gelbooru.com is using the anti adblock, however easylist implemented a block on the iframe with the following rule:
extremetech.com,gelbooru.com,hawtcelebs.com,moviemistakes.com,wccftech.com##iframe[height="250"]

Motherless is also effected with this rule:
motherless.com##iframe[style]

We currently have no way around this as its not as simple as renaming the backend php or js script. Is there a way to pass the ad with something random and not a iframe that can be blocked like this?

**Comment by golikov** [comment]
Yes. Coming soon https://github.com/EXADS/exads-adblock/tree/new_placeholder

**Comment by golikov** [comment]
Should be ok now

**Comment by slayerduck** [comment]
I updated but ##iframe[height="250"] still kills the 300x250 blocks
